env:
  es6: true
  browser: false
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jest/recommended'
parser: '@typescript-eslint/parser'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
ignorePatterns:
  - 'src/__mocks__/**/*'
  - 'src/types/**/*'
plugins:
  - 'prettier'
  - 'jest'
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/explicit-module-boundary-types': off
